several changes to make geant4 and ROOT to work

diff --git a/create-env b/create-env
--- a/create-env
+++ b/create-env
@@ -341,15 +341,32 @@ export PATH=$target_dir/bin:$PATH
 
 announce "Installing ROOT"
 cd /tmp
-rm -rf /tmp/root
+rm -rf /opt/root
 wget -nv -O root_v${root_version}.Linux-almalinux8.10-x86_64-gcc8.5.tar.gz \
     https://root.cern/download/root_v${root_version}.Linux-almalinux8.10-x86_64-gcc8.5.tar.gz
-tar xzf root_v${root_version}.Linux-almalinux8.10-x86_64-gcc8.5.tar.gz -C /tmp
-mv /tmp/root ${target_dir}/root
+tar xzf root_v${root_version}.Linux-almalinux8.10-x86_64-gcc8.5.tar.gz -C /opt
+mv /opt/root ${target_dir}/root
 rm -f root_v${root_version}.Linux-almalinux8.10-x86_64-gcc8.5.tar.gz
 
+announce "Installing custom ROOT setup"
+thisroot_source=
+if [ -f ./thisroot.sh ]; then
+    thisroot_source=./thisroot.sh
+elif [ -f /tmp/thisroot.sh ]; then
+    thisroot_source=/tmp/thisroot.sh
+fi
+
+if [ "x$thisroot_source" = "x" ]; then
+    echo "ERROR: custom thisroot.sh not found; refusing to use ROOT's default thisroot.sh" >&2
+    exit 1
+fi
+
+mkdir -p ${target_dir}/bin
+sed "s;^ROOTSYS=.*;ROOTSYS=${target_dir}/root;" "$thisroot_source" > ${target_dir}/bin/thisroot.sh
+chmod +x ${target_dir}/bin/thisroot.sh
+
 # Ensure ROOT works
-. ${target_dir}/root/bin/thisroot.sh
+. ${target_dir}/bin/thisroot.sh
 installed_root_version=$(root-config --version | tr '/' '.')
 if [ "$installed_root_version" != "$root_version" ]; then
     echo "Unexpected ROOT version: $installed_root_version" >&2
@@ -376,34 +393,41 @@ cmake -DCMAKE_INSTALL_PREFIX=$target_dir \
       /tmp/geant4.${geant4_version}
 make -j8
 make install
+
+# Geant4 10.06 still exports -std=c++11 in geant4make/geant4-config on EL8.
+sed -i 's/-std=c++11/-std=c++17/g' "${target_dir}/bin/geant4-config"
+sed -i 's/-std=c++11/-std=c++17/g' "${target_dir}"/share/Geant4-*/geant4make/config/sys/Linux-g++.gmk
+sed -i 's/-std=c++11/-std=c++17/g' "${target_dir}"/lib*/Geant4-*/Geant4Config.cmake
+
+# Fail early if the install still exports C++11
+if "${target_dir}/bin/geant4-config" --cflags | grep -q -- '-std=c++11'; then
+    echo "ERROR: Installed Geant4 still exports -std=c++11" >&2
+    exit 1
+fi
+
 cd /tmp
 rm -rf geant4.${geant4_version}.tar.gz geant4.${geant4_version}
 
 announce "Adding ROOT/Geant4 setup"
-cat > ${target_dir}/bin/thisroot.sh <<EOF
-#!/bin/bash
-. ${target_dir}/root/bin/thisroot.sh
-export CLING_STANDARD_PCH=none
-EOF
-chmod +x ${target_dir}/bin/thisroot.sh
 
-# Source MC env on container start
-cat > /.singularity.d/env/zzz-60-xenon-montecarlo.sh <<EOF
+cat >> ${target_dir}/setup.sh <<EOF
 
-#!/bin/sh
-if [ "x\$XENON_DEBUG" != "x" ]; then
-    echo
-    env
-    echo
-fi
-if [ \$XENON_SOURCE -eq 1 ]; then
-    START_DIR=\$PWD
-    cd ${target_dir}/bin
-    . ./thisroot.sh
-    . ./geant4.sh
-    cd ${target_dir}/share/Geant4-*/geant4make/
-    . ./geant4make.sh
-    cd \$START_DIR
+# ROOT / Geant4
+if [ -f ${target_dir}/bin/thisroot.sh ] && [ -f ${target_dir}/bin/geant4.sh ]; then
+    XENON_START_DIR=\$PWD
+    . ${target_dir}/bin/thisroot.sh
+    . ${target_dir}/bin/geant4.sh
+
+    for XENON_GEANT4MAKE_DIR in ${target_dir}/share/Geant4-*/geant4make; do
+        if [ -f "\$XENON_GEANT4MAKE_DIR/geant4make.sh" ]; then
+            cd "\$XENON_GEANT4MAKE_DIR"
+            . ./geant4make.sh
+            break
+        fi
+    done
+
+    cd "\$XENON_START_DIR"
+    unset XENON_START_DIR XENON_GEANT4MAKE_DIR
 fi
 EOF
 
