using thisroot.sh the same way used in montecarlo_environmet

diff --git a/create-env b/create-env
--- a/create-env
+++ b/create-env
@@ -352,30 +352,38 @@ tar xzf root_v${root_version}.Linux-almalinux8.10-x86_64-gcc8.5.tar.gz -C /opt
 mv /opt/root ${target_dir}/root
 rm -f root_v${root_version}.Linux-almalinux8.10-x86_64-gcc8.5.tar.gz
 
-announce "Installing custom ROOT setup"
-thisroot_source=
-if [ -f ./thisroot.sh ]; then
-    thisroot_source=./thisroot.sh
-elif [ -f /tmp/thisroot.sh ]; then
-    thisroot_source=/tmp/thisroot.sh
-fi
-
-if [ "x$thisroot_source" = "x" ]; then
-    echo "ERROR: custom thisroot.sh not found; refusing to use ROOT's default thisroot.sh" >&2
-    exit 1
-fi
-
-mkdir -p ${target_dir}/bin
-sed "s;^ROOTSYS=.*;ROOTSYS=${target_dir}/root;" "$thisroot_source" > ${target_dir}/bin/thisroot.sh
-chmod +x ${target_dir}/bin/thisroot.sh
-
-# Ensure ROOT works
-. ${target_dir}/bin/thisroot.sh
+cd ${target_dir}/bin
+. ./thisroot.sh
 installed_root_version=$(root-config --version | tr '/' '.')
 if [ "$installed_root_version" != "$root_version" ]; then
     echo "Unexpected ROOT version: $installed_root_version" >&2
     exit 1
 fi
+
+# announce "Installing custom ROOT setup"
+# thisroot_source=
+# if [ -f ./thisroot.sh ]; then
+#     thisroot_source=./thisroot.sh
+# elif [ -f /tmp/thisroot.sh ]; then
+#     thisroot_source=/tmp/thisroot.sh
+# fi
+
+# if [ "x$thisroot_source" = "x" ]; then
+#     echo "ERROR: custom thisroot.sh not found; refusing to use ROOT's default thisroot.sh" >&2
+#     exit 1
+# fi
+
+# mkdir -p ${target_dir}/bin
+# sed "s;^ROOTSYS=.*;ROOTSYS=${target_dir}/root;" "$thisroot_source" > ${target_dir}/bin/thisroot.sh
+# chmod +x ${target_dir}/bin/thisroot.sh
+
+# # Ensure ROOT works
+# . ${target_dir}/bin/thisroot.sh
+# installed_root_version=$(root-config --version | tr '/' '.')
+# if [ "$installed_root_version" != "$root_version" ]; then
+#     echo "Unexpected ROOT version: $installed_root_version" >&2
+#     exit 1
+# fi
 
 announce "Installing GEANT4"
 cd /tmp
